    export enum ReportSubjectType {
        BEHAVIOR = 'BEHAVIOR',
        LATE_ARRIVAL = 'LATE_ARRIVAL',
        NO_SHOW = 'NO_SHOW',
        DANGEROUS_DRIVING = 'DANGEROUS_DRIVING',
        RIDE = 'RIDE',
        VEHICLE_MALFUNCTION = 'VEHICLE_MALFUNCTION',
        IMPROPER_CONDUCT = 'IMPROPER_CONDUCT',
        POOR_COMMUNICATION = 'POOR_COMMUNICATION',
        TRAFFIC_VIOLATION = 'TRAFFIC_VIOLATION',
        OTHER = 'OTHER',
    }
